"use client";

import { createContext, useContext, useEffect, useState } from "react";
import { SharedState } from "./types";
import { useQuery } from "@tanstack/react-query";
import { fetchArtisteAlbums, getArtistes } from "@/helpers/api-controller";
import { getAllActiveMerch, getExchangeRates } from "./api-controller";

const AppContext = createContext<SharedState>({} as SharedState);

export const AppWrapper = ({ children }: { children: React.ReactNode }) => {
  const [cart, setcart] = useState<any>({ items: [], discount: "" });
  const [user, setuser] = useState<any>(undefined);

  const { data: albumData, isError: albumError } = useQuery({
    queryKey: ["awg-tracks"],
    queryFn: async () => fetchArtisteAlbums("4em6zsRUNAPC2YTfqdCpow"),
  });

  const { data: merchData } = useQuery({
    queryKey: ["merch"],
    queryFn: () => getAllActiveMerch(),
  });

  const { data: artistesData } = useQuery({
    queryKey: ["artistes"],
    queryFn: () => getArtistes(),
  });

  const artistes = artistesData?.artistes;
  const all_merch = merchData?.merch;

  const awgProjects = albumData?.items?.map((item: any) => {
    return {
      project: item?.album_group,
      title: item?.name,
      art: item?.images[1]?.url,
      artist: item?.artists?.map((a: any) => a.name)?.join(" & "),
      link: item?.external_urls?.spotify,
    };
  });

  const [exchangeRates, setExchangeRates] = useState<{ [key: string]: number }>(
    {}
  );

  const [currency, setCurrency] = useState("NGN");

  const fetchRates = async () => {
    const rates = await getExchangeRates();
    return rates;
  };

  const [selectedMerch, setSelectedMerch] = useState<any>();

  useEffect(() => {
    const rates = fetchRates().then((data) => {
      const {
        aed,
        afn,
        all,
        amd,
        ang,
        aoa,
        ars,
        ats,
        aud,
        awg,
        azm,
        azn,
        bam,
        bbd,
        bdt,
        bef,
        bgn,
        bhd,
        bif,
        bmd,
        bnd,
        bob,
        brl,
        bsd,
        btn,
        bwp,
        byn,
        byr,
        bzd,
        cad,
        cdf,
        chf,
        clp,
        cnh,
        cny,
        cop,
        crc,
        cuc,
        cup,
        cve,
        cyp,
        czk,
        dem,
        djf,
        dkk,
        dop,
        dzd,
        eek,
        egp,
        ern,
        esp,
        etb,
        eur,
        fim,
        fjd,
        fkp,
        frf,
        gbp,
        gel,
        ggp,
        ghc,
        ghs,
        gip,
        gmd,
        gnf,
        grd,
        gtq,
        gyd,
        hkd,
        hnl,
        hrk,
        htg,
        huf,
        idr,
        iep,
        ils,
        imp,
        inr,
        iqd,
        irr,
        isk,
        itl,
        jep,
        jmd,
        jod,
        jpy,
        kes,
        kgs,
        khr,
        kmf,
        kpw,
        krw,
        kwd,
        kyd,
        kzt,
        lak,
        lbp,
        lkr,
        lrd,
        lsl,
        ltl,
        luf,
        lvl,
        lyd,
        mad,
        mdl,
        mga,
        mgf,
        mkd,
        mmk,
        mnt,
        mop,
        mro,
        mru,
        mtl,
        mur,
        mvr,
        mwk,
        mxn,
        mxv,
        myr,
        mzm,
        mzn,
        nad,
        nio,
        nlg,
        nok,
        npr,
        nzd,
        omr,
        pab,
        pen,
        pgk,
        php,
        pkr,
        pln,
        pte,
        pyg,
        qar,
        rol,
        ron,
        rsd,
        rub,
        rwf,
        sar,
        sbd,
        scr,
        sdd,
        sdg,
        sek,
        sgd,
        shp,
        sit,
        skk,
        sle,
        sll,
        sos,
        srd,
        srg,
        std,
        stn,
        svc,
        syp,
        szl,
        thb,
        tjs,
        tmm,
        tmt,
        tnd,
        top,
        trl,
        ttd,
        tvd,
        twd,
        tzs,
        uah,
        ugx,
        usd,
        uyu,
        uzs,
        veb,
        ved,
        vef,
        ves,
        vnd,
        vuv,
        wst,
        xaf,
        xag,
        xau,
        xcd,
        xdr,
        xof,
        xpd,
        xpf,
        xpt,
        yer,
        zar,
        zmk,
        zmw,
        zwd,
        zwg,
        zwl,
      } = data?.ngn || {};

      setExchangeRates({
        aed,
        afn,
        all,
        amd,
        ang,
        aoa,
        ars,
        ats,
        aud,
        awg,
        azm,
        azn,
        bam,
        bbd,
        bdt,
        bef,
        bgn,
        bhd,
        bif,
        bmd,
        bnd,
        bob,
        brl,
        bsd,
        btn,
        bwp,
        byn,
        byr,
        bzd,
        cad,
        cdf,
        chf,
        clp,
        cnh,
        cny,
        cop,
        crc,
        cuc,
        cup,
        cve,
        cyp,
        czk,
        dem,
        djf,
        dkk,
        dop,
        dzd,
        eek,
        egp,
        ern,
        esp,
        etb,
        eur,
        fim,
        fjd,
        fkp,
        frf,
        gbp,
        gel,
        ggp,
        ghc,
        ghs,
        gip,
        gmd,
        gnf,
        grd,
        gtq,
        gyd,
        hkd,
        hnl,
        hrk,
        htg,
        huf,
        idr,
        iep,
        ils,
        imp,
        inr,
        iqd,
        irr,
        isk,
        itl,
        jep,
        jmd,
        jod,
        jpy,
        kes,
        kgs,
        khr,
        kmf,
        kpw,
        krw,
        kwd,
        kyd,
        kzt,
        lak,
        lbp,
        lkr,
        lrd,
        lsl,
        ltl,
        luf,
        lvl,
        lyd,
        mad,
        mdl,
        mga,
        mgf,
        mkd,
        mmk,
        mnt,
        mop,
        mro,
        mru,
        mtl,
        mur,
        mvr,
        mwk,
        mxn,
        mxv,
        myr,
        mzm,
        mzn,
        nad,
        ngn: 1,
        nio,
        nlg,
        nok,
        npr,
        nzd,
        omr,
        pab,
        pen,
        pgk,
        php,
        pkr,
        pln,
        pte,
        pyg,
        qar,
        rol,
        ron,
        rsd,
        rub,
        rwf,
        sar,
        sbd,
        scr,
        sdd,
        sdg,
        sek,
        sgd,
        shp,
        sit,
        skk,
        sle,
        sll,
        sos,
        srd,
        srg,
        std,
        stn,
        svc,
        syp,
        szl,
        thb,
        tjs,
        tmm,
        tmt,
        tnd,
        top,
        trl,
        ttd,
        tvd,
        twd,
        tzs,
        uah,
        ugx,
        usd,
        uyu,
        uzs,
        veb,
        ved,
        vef,
        ves,
        vnd,
        vuv,
        wst,
        xaf,
        xag,
        xau,
        xcd,
        xdr,
        xof,
        xpd,
        xpf,
        xpt,
        yer,
        zar,
        zmk,
        zmw,
        zwd,
        zwg,
        zwl,
      });
    });
  }, []);

  const sharedState: SharedState = {
    artistes,
    all_merch,
    awgProjects,
    cart,
    setcart,
    user,
    setuser,
    exchangeRates,
    setExchangeRates,
    currency,
    setCurrency,
    selectedMerch,
    setSelectedMerch,
  };

  return (
    <AppContext.Provider value={sharedState}>{children}</AppContext.Provider>
  );
};

export const useAppContext = () => useContext(AppContext);
