"use client";

import { createContext, useContext, useState } from "react";
import { CartItemProps, MerchProps, SharedState } from "./types";
import { useQuery } from "@tanstack/react-query";
import { fetchArtisteAlbums } from "@/app/utils/api";

const AppContext = createContext<SharedState>({} as SharedState);

export const AppWrapper = ({ children }: { children: React.ReactNode }) => {
  const artistes = [
    {
      artisteSpotifyId: "3LOm0AZjpwVQebvkyanjDy",
      name: "ODUMODUBLVCK",
      bio: `Born in Lagos and raised in Abuja, Nigeria, ODUMODUBLVCK has emerged as a compelling voice from the nation's capital over the past decade. A trailblazer of Drill music in Nigeria, he pioneers a unique genre he dubs Okporoko Rhythms, blending Hip-Hop with influences from Grime, Fela Kuti’s Afrobeat, and Progressive R&B. His deep, introspective lyricism shines through every track and performance. His larger-than-life persona and distinctive, menacing growl have earned him comparisons to the legendary DMX. ODUMODUBLVCK’s latest release, "Declan Rice," has received acclaim, with shoutouts from icons like Wizkid, Skepta, and even Declan Rice himself. Since his debut single in 2017, he’s been on a mission to tell his story, breaking streaming records. "Declan Rice" topped Apple Music and Spotify’s Top 100 charts upon release. Aligned with NATIVE RECORDS and collaborator TEEZEE, ODUMODUBLVCK is taking the industry by storm. Proudly representing Abuja, he’s proving there are no rules to success, leading his Anti-World Gangsters and Blvck Sheep Music collectives to new heights.`,
      image1: "/kala/kala1.png",
      image2: "/kala/kala2.jpg",
      socials: [
        {
          name: "X",
          link: "https://x.com/",
        },
        {
          name: "Instagram",
          link: "https://instagram.com/",
        },
        {
          name: "Snapchat",
          link: "https://snapchat.com/",
        },
        {
          name: "Tiktok",
          link: "https://tiktok.com/",
        },
      ],
      projects: [
        {
          artist: "ODUMODUBLVCK",
          project: "Album",
          art: "/kala/eziokwu-uncut.jpeg",
          title: "Eziokwu (Uncut)",
        },
        {
          artist: "ODUMODUBLVCK",
          project: "Album",
          art: "/kala/eziokwu.jpeg",
          title: "Eziokwu",
        },
        {
          artist: "ODUMODUBLVCK",
          project: "Single",
          art: "/kala/technician.jpeg",
          title: "Technician",
        },
      ],
      videoIds: ["UXOO0UaXwGo", "SNoS_RauCw8", "Ts8keLThN_s", "pr5YwkazQbw"],
    },
    {
      artisteSpotifyId: "2UausQcu26M23zEr5rUODB",
      name: "REEPLAY",
      bio: `Reeplay is an abuja based artist in Nigeria. His acronym, Reeplay, stands for "RAW EVOLVED ENERGY PLAYING LOUD ALL YEAR". Reeplay is recognized for his dynamic fusion of genres and authentic storytelling. His music seamlessly blends hip-hop, Afrobeat, and soul, reflecting his commitment to innovative and honest expression. Reeplay is a top member of the Anti world gangstars music collective based in Abuja alongside ODUMODUBLVCK, AGUNNA, SHAGBA, FATBOY E & CROSS.`,
      image1: "/reeplay/reeplay1.png",
      image2: "/reeplay/reeplay2.jpg",
      socials: [
        {
          name: "X",
          link: "https://x.com/",
        },
        {
          name: "Instagram",
          link: "https://instagram.com/",
        },
        {
          name: "Snapchat",
          link: "https://snapchat.com/",
        },
        {
          name: "Tiktok",
          link: "https://tiktok.com/",
        },
      ],
      projects: [
        {
          artist: "REEPLAY",
          project: "Album",
          art: "/reeplay/jig-is-up.png",
          title: "The Jig Is Up",
        },
        {
          artist: "REEPLAY",
          project: "Album",
          art: "/reeplay/who-is-reeplay.png",
          title: "Who Is Reeplay",
        },
        {
          artist: "REEPLAY x CASH'N'OUT",
          project: "Single",
          art: "/reeplay/show-must-go-on.png",
          title: "Show Must Go On",
        },
      ],
      videoIds: ["4QbKE8XX9UY", "_AdfES3wFU8", "9_mcBuAjX9Y", "Bp1CPGPGdg8"],
    },
    {
      artisteSpotifyId: "1CENr91YcmLqLMk3fPeqze",
      name: "AGUNNA",
      bio: `Rapper, singer, and songwriter Agunna is an electrifying performer from Abuja, Nigeria. Known for his versatile sound, he blends Hip-hop, R&B, Afro-Swing, Afrobeat, and Alternative influences. Agunna made his mark in 2017 with the collective Blvcksheep, releasing the mixtape TABS (To All Blvcksheep) featuring the hit single "Farabale," which became an anthem in Abuja. In 2018, Agunna joined forces with Replay, Cross, and Fatboy-E to form the Antiworld Gangstars, a powerhouse collective that showcased their talents on the acclaimed album Gang Business. This collaboration solidified their influence in the Abuja music scene. Agunna’s dynamic style and captivating performances have earned him a dedicated following. His seamless transitions between genres and commitment to authenticity continue to push the boundaries of contemporary music, making him a rising star in Nigeria's music industry.`,
      image1: "/ag/ag1.png",
      image2: "/ag/ag2.jpg",
      socials: [
        {
          name: "X",
          link: "https://x.com/",
        },
        {
          name: "Instagram",
          link: "https://instagram.com/",
        },
        {
          name: "Snapchat",
          link: "https://snapchat.com/",
        },
        {
          name: "Tiktok",
          link: "https://tiktok.com/",
        },
      ],
      projects: [
        {
          artist: "ODUMODUBLVCK",
          project: "Album",
          art: "/kala/eziokwu-uncut.jpeg",
          title: "Eziokwu (Uncut)",
        },
        {
          artist: "ODUMODUBLVCK",
          project: "Album",
          art: "/kala/eziokwu.jpeg",
          title: "Eziokwu",
        },
        {
          artist: "ODUMODUBLVCK",
          project: "Single",
          art: "/kala/technician.jpeg",
          title: "Technician",
        },
      ],
      videoIds: ["WxvDJLYrNgc", "03VgX_mCGlw", "Z4JMNd8F-Uk", "5GPJM7ztA7M"],
    },
    {
      artisteSpotifyId: "7oQ6PiDrtScurCpBvMtf5b",
      name: "FATBOY E",
      bio: `"Fatboy E," a prominent member of the Abuja Stronghold collective AntiWorldGangstars, originally hails from Port Harcourt but currently resides in Abuja. Renowned for his clever and infectious hooks, showcased notably on tracks like "Dull" and "Change Am" from Antiworldgangsters' sophomore project "Gang Business," he's made a mark in the Nigerian music scene. His EP "Fatboy Energy" underscores his versatility as a rapper, singer, and songwriter. Noteworthy collaborations include featuring on Odumodublvck’s "Shokolokobangoshe" from the "Time and Chance" EP, as well as handling the hook alongside Odumodublvck on the smash hit "Hotel Lobby" from the "Eziokwu" album. With over 15k views on YouTube, Fatboy E continues to captivate audiences with his unique style and magnetic presence.`,
      image1: "/fatboy/fatboy1.png",
      image2: "/fatboy/fatboy2.png",
      socials: [
        {
          name: "X",
          link: "https://x.com/",
        },
        {
          name: "Instagram",
          link: "https://instagram.com/",
        },
        {
          name: "Snapchat",
          link: "https://snapchat.com/",
        },
        {
          name: "Tiktok",
          link: "https://tiktok.com/",
        },
      ],
      projects: [
        {
          artist: "ODUMODUBLVCK",
          project: "Album",
          art: "/kala/eziokwu-uncut.jpeg",
          title: "Eziokwu (Uncut)",
        },
        {
          artist: "ODUMODUBLVCK",
          project: "Album",
          art: "/kala/eziokwu.jpeg",
          title: "Eziokwu",
        },
        {
          artist: "ODUMODUBLVCK",
          project: "Single",
          art: "/kala/technician.jpeg",
          title: "Technician",
        },
      ],
      videoIds: ["DqMtbVI1UyI", "UZLgpZ8zfXU", "jLmmOePLGBs", "_2mYAZGefRo"],
    },
    {
      artisteSpotifyId: "5GxgrhXvXlieEQX1KThYzh",
      name: "SHAGBA",
      bio: `Born in Kano State and raised in Makurdi, Shagba moved to Abuja as a teenager. Influenced early by Sisqo and 2Face’s "Grass to Grace" album, he recorded his first song at 16. Shagba released an EP and a mixtape, then joined Blvck Sheep Music. Later, he partnered with Izzgaju to form ANTIWORLD Gangsters. A business graduate from Ajayi Crowther University, Shagba's discography includes "The SBEE EP," "Son of Sam," "MARKTOWNdon EP," and "Alcohol, Drugs, and STDs." His singles, such as "Drunk," "Booze," and "Money on My Mind," have contributed to over 200k collective plays. Social media: @supershagba on all platforms`,
      image1: "/shagba/shagba1.png",
      image2: "/shagba/shagba2.jpg",
      socials: [
        {
          name: "X",
          link: "https://x.com/",
        },
        {
          name: "Instagram",
          link: "https://instagram.com/",
        },
        {
          name: "Snapchat",
          link: "https://snapchat.com/",
        },
        {
          name: "Tiktok",
          link: "https://tiktok.com/",
        },
      ],
      projects: [
        {
          artist: "ODUMODUBLVCK",
          project: "Album",
          art: "/kala/eziokwu-uncut.jpeg",
          title: "Eziokwu (Uncut)",
        },
        {
          artist: "ODUMODUBLVCK",
          project: "Album",
          art: "/kala/eziokwu.jpeg",
          title: "Eziokwu",
        },
        {
          artist: "ODUMODUBLVCK",
          project: "Single",
          art: "/kala/technician.jpeg",
          title: "Technician",
        },
      ],
      videoIds: ["0zULMlBf-A4", "_F2t6WeTHyw", "AbCYqhQQs54", "eHcPCDU9ueM"],
    },
    {
      artisteSpotifyId: "4em6zsRUNAPC2YTfqdCpow",
      name: "CROSS",
      bio: `Omaki Farouk Ateiza, popularly known as Cross, is a music producer and mix engineer based in Abuja. Hailing from Nasarawa state, he was raised in Abuja and Kwara state. As a founding member of the Abuja hip hop collective "ANTIWORLD GANGSTARS," he has shaped the sounds of various artists in the drill, grime, and hip hop scenes. He produced hits like “Dull” from the Antiworld Gangstars' debut album “Gang Business,” and mixed most of the tracks. While at Afe Babalola University, he collaborated with rapper Eeskay, resulting in tracks like "9 Lives” and "Ready When You're Ready.” His notable work includes producing hits on Odumodublvck’s debut album "Eziokwu," such as WotoWoto Seasoning, Mc Oluomo, and Hotel Lobby. Upcoming projects include the 'Danger EP' by Fat Boy E and Reeplay, a solo sophomore project, and another AWG project. Cross cites 50 Cent and G-Unit as major influences, and Timbaland's "Shock Value 2" as his inspiration to produce.`,
      image1: "/cross/cross1.png",
      image2: "/cross/cross2.jpg",
      socials: [
        {
          name: "X",
          link: "https://x.com/",
        },
        {
          name: "Instagram",
          link: "https://instagram.com/",
        },
        {
          name: "Snapchat",
          link: "https://snapchat.com/",
        },
        {
          name: "Tiktok",
          link: "https://tiktok.com/",
        },
      ],
      projects: [
        {
          artist: "ODUMODUBLVCK",
          project: "Album",
          art: "/kala/eziokwu-uncut.jpeg",
          title: "Eziokwu (Uncut)",
        },
        {
          artist: "ODUMODUBLVCK",
          project: "Album",
          art: "/kala/eziokwu.jpeg",
          title: "Eziokwu",
        },
        {
          artist: "ODUMODUBLVCK",
          project: "Single",
          art: "/kala/technician.jpeg",
          title: "Technician",
        },
      ],
    },
  ];
  const all_merch: MerchProps[] = [
    {
      image: "/gang/gang-merch1.png",
      name: "AWG B/Y JERSEY",
      price: 45000,
      artiste: "awg",
      category: "jersey",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00000",
    },
    {
      image: "/gang/gang-merch2.png",
      name: "Property of AWG Tee",
      price: 45000,
      artiste: "awg",
      category: "tshirt",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00001",
    },
    {
      image: "/gang/gang-merch3.png",
      name: "AWG ALT JERSEY",
      price: 45000,
      artiste: "awg",
      category: "jersey",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00002",
    },
    {
      image: "/gang/awg-rap-attack.png",
      name: "AWG Rap Attack Tee",
      price: 45000,
      artiste: "awg",
      category: "tshirt",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00003",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "Who De Check Am Hoodie",
      price: 45000,
      artiste: "Reeplay",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00000",
    },
    {
      image: "/dummy/dummymerch2.jpg",
      name: "Jig Is Up Head Warmer",
      price: 45000,
      artiste: "Reeplay",
      category: "hat",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00001",
    },
    {
      image: "/dummy/dummymerch3.jpg",
      name: "Light My Bars Jacket",
      price: 45000,
      artiste: "Reeplay",
      category: "hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00002",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "Who De Check Am Hoodie",
      price: 45000,
      artiste: "Reeplay",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00003",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "Eziokwu Hoodie",
      price: 45000,
      artiste: "Odumodublvck",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00004",
    },
    {
      image: "/dummy/dummymerch2.jpg",
      name: "Kala Head Warmer",
      price: 45000,
      artiste: "Odumodublvck",
      category: "hat",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00005",
    },
    {
      image: "/dummy/dummymerch3.jpg",
      name: "Light My Bars Jacket",
      price: 45000,
      artiste: "Odumodublvck",
      category: "hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00006",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "Who De Check Am Hoodie",
      price: 45000,
      artiste: "Odumodublvck",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00007",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "T's & C's Hoodie",
      price: 45000,
      artiste: "Fatboy E",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00008",
    },
    {
      image: "/dummy/dummymerch2.jpg",
      name: "Agege Head Warmer",
      price: 45000,
      artiste: "Fatboy E",
      category: "hat",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00009",
    },
    {
      image: "/dummy/dummymerch3.jpg",
      name: "Big Zoot Jacket",
      price: 45000,
      artiste: "Fatboy E",
      category: "hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00010",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "Who De Check Am Hoodie",
      price: 45000,
      artiste: "Fatboy E",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00011",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "4D Cruise Hoodie",
      price: 45000,
      artiste: "Agunna",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00012",
    },
    {
      image: "/dummy/dummymerch2.jpg",
      name: "Tipper Head Warmer",
      price: 45000,
      artiste: "Agunna",
      category: "hat",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00013",
    },
    {
      image: "/dummy/dummymerch3.jpg",
      name: "Disrespect Jacket",
      price: 45000,
      artiste: "Agunna",
      category: "hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00014",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "Who De Check Am Hoodie",
      price: 45000,
      artiste: "Agunna",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00015",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "Marktown Hoodie",
      price: 45000,
      artiste: "Shagba",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00016",
    },
    {
      image: "/dummy/dummymerch2.jpg",
      name: "Kala Head Warmer",
      price: 45000,
      artiste: "Shagba",
      category: "hat",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00017",
    },
    {
      image: "/dummy/dummymerch3.jpg",
      name: "Light My Bars Jacket",
      price: 45000,
      artiste: "Shagba",
      category: "hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00018",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "Who De Check Am Hoodie",
      price: 45000,
      artiste: "Shagba",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00019",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "You Dey Crase Hoodie",
      price: 45000,
      artiste: "Cross",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00020",
    },
    {
      image: "/dummy/dummymerch2.jpg",
      name: "Kala Head Warmer",
      price: 45000,
      artiste: "Cross",
      category: "hat",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00021",
    },
    {
      image: "/dummy/dummymerch3.jpg",
      name: "Light My Bars Jacket",
      price: 45000,
      artiste: "Cross",
      category: "hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00022",
    },
    {
      image: "/dummy/dummymerch.jpg",
      name: "Who De Check Am Hoodie",
      price: 45000,
      artiste: "Cross",
      category: "Hoodie",
      quantity: 10,
      country: "Nigeria",
      city: "Abuja",
      sizes: ["s", "m", "l", "xl", "xxl"],
      id: "00023",
    },
  ];
  const [cart, setcart] = useState<CartItemProps[]>([]);

  const { data: albumData, isError: albumError } = useQuery({
    queryKey: ["awg-tracks"],
    queryFn: async () => fetchArtisteAlbums("4em6zsRUNAPC2YTfqdCpow"),
  });

  const awgProjects = albumData?.items?.map((item: any) => {
    return {
      project: item?.album_group,
      title: item?.name,
      art: item?.images[1]?.url,
      artist: item?.artists?.map((a: any) => a.name)?.join(" & "),
      link: item?.external_urls?.spotify,
    };
  });

  const sharedState: SharedState = {
    artistes,
    all_merch,
    awgProjects,
    cart,
    setcart,
  };

  return (
    <AppContext.Provider value={sharedState}>{children}</AppContext.Provider>
  );
};

export const useAppContext = () => useContext(AppContext);
