import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PreHeader from "@/app/ui/pre-header";
import Footer from "./ui/footer";
import { AppWrapper } from "@/helpers/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ANTIWORLD GANGSTARS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>
          {/* <PreHeader text="THE MOST SOLID GANG YOU'LL EVER SEE" /> */}
          {children}
          <Footer />
        </AppWrapper>
      </body>
    </html>
  );
}
